const AppConstants = {}
AppConstants.install = function (Vue, options) {
    Vue.prototype.appConstants = {
        translations: {
            fr: {
                jobProperties: {
                    categorie: 'Catégorie',
                    canton: 'Canton',
                    levelOfExperience: "Niveau d'expérience",
                    duration: 'Durée',
                    clientProjectContext: 'Projet et contexte client',
                    yourRole: 'Votre rôle',
                    yourProfil: 'Votre profil',
                    recruter: 'Recruteur',
                    contactName: 'Prénom et',
                    contactLastName: 'nom',
                    contactEmail: 'Adresse e-mail',
                    contactMobile: 'Téléphone mobile',
                    contactTelephone: 'Téléphone fixe',
                },
                defaultJobPost: {
                    title: `Candidatures spontanées`,
                    text: `Vous n'avez pas trouvé un job correspondant à votre profil ? Déposez votre candidature spontanée.`
                },
                fullName: 'Nom complet',
                readMore: 'Lire plus',
                viewMore: 'Voir plus',
                otherArticles: 'Autres articles…',
                seeAllNews: 'Voir toutes les news',
                year: 'Année',
                copyright: 'Api SA. Tous droits réservés',
                partnersTitle: 'Partenaires',
                partnersSubTitle: 'Évolution vers un service global',
                noResult: 'Aucun résultat',
                search: 'Rechercher',
                filters: 'Filtres',
                return: 'Retour aux',
                remoteSupport: `Support à distance`,
                deleteEverything: 'Tout effacer',
                send: 'Envoyer',
                findUsOn: 'Retrouvez-nous sur',
                subscribe: "S'abonner à notre newsletter",
                form: {
                    firstName: 'Prénom *',
                    lastName: 'Nom *',
                    topic: 'Sujet',
                    email: 'Adresse e-mail',
                    message: 'Message',
                    contactConfirmationMessage: 'Votre demande a bien été envoyée',
                    contactErrorMessage: 'Erreur',
                    selectOne: 'Prise de contact commercial',
                    selectTwo: 'Prise de contact candidat',
                    selectThree: 'Information API',
                    selectFour: 'Autres',
                },
                subscribeForm: {
                    success: 'Vous vous êtes inscrit avec succès à notre newsletter!',
                    error: `Quelque chose s'est mal passé. Veuillez réessayer!`,
                    alreadyExist: 'Vous êtes déjà abonné!'
                },
                deleteEverything: 'Tout effacer',
                contact: 'Contact',
                learnMore: 'En savoir plus',
                preferences: 'Préférences',
                necessaryCookies: 'Cookies nécessaires',
                analytics: 'Analytics',
                privacyPolicy: 'Politique de confidentialité',
                supportClient: 'Support client :'
            },
            en: {
                jobProperties: {
                    categorie: 'Categorie',
                    canton: 'Canton',
                    levelOfExperience: 'Level of experience',
                    duration: 'Duration',
                    clientProjectContext: 'Project and client context',
                    yourRole: 'Your role',
                    yourProfil: 'Your profile',
                    recruter: 'Recruiter',
                    contactName: 'First name and',
                    contactLastName: 'last name',
                    contactEmail: 'Email address',
                    contactMobile: 'Mobile phone',
                    contactTelephone: 'Home phone',                                        
                },
                defaultJobPost: {
                    title: `Spontaneous applications`,
                    text: `You haven't found a job that matches your profile? Submit your spontaneous application.`
                },                                
                fullName: 'Full name',
                readMore: 'Read more',
                viewMore: 'See more',
                otherArticles: 'Other articles…',
                seeAllNews: 'See all news',
                year: 'Year',
                copyright: 'Api SA. All rights reserved',
                partnersTitle: 'Partners',
                partnersSubTitle: 'Evolution towards a global service',
                noResult: 'No Result',
                search: 'Search',
                filters: 'Filters',
                return: 'Back to',
                remoteSupport: `Remote support`,
                deleteEverything: 'Erase everything',
                send: 'Submit',
                findUsOn: 'Find us on',
                subscribe: 'Subscribe to our newsletter',
                form: {
                    firstName: 'First Name *',
                    lastName: 'Last Name *',
                    topic: 'Subject',
                    email: 'Email address',
                    message: 'Message',
                    contactConfirmationMessage: 'Your request has been sent',
                    contactErrorMessage: 'Error',
                    selectOne: 'Commercial contact',
                    selectTwo: 'Candidate contact',
                    selectThree: 'API information',
                    selectFour: 'Other',
                },
                subscribeForm: {
                    success: 'You have successfully subscribed to our newsletter!',
                    error: 'Something went wrong. Please try again!',
                    alreadyExist: 'You already subscribed!'
                },                
                deleteEverything: 'Erase everything',
                contact: 'Contact',
                learnMore: 'Learn more',
                preferences: 'Preferences',
                necessaryCookies: 'Necessary ookies',
                analytics: 'Analytics',
                privacyPolicy: 'Privacy policy',
                supportClient: 'Client support:'
            },
            de: {
                jobProperties: {
                    categorie: 'Kategorie',
                    canton: 'Kanton',
                    levelOfExperience: 'Niveau der Erfahrung',
                    duration: 'Dauer',
                    clientProjectContext: 'Projekt und Kundenkontext',
                    yourRole: 'Ihre Rolle',
                    yourProfil: 'Ihr Profil',
                    recruter: 'Personalvermittler',         
                    contactName: 'Vorname und',
                    contactLastName: 'Name',
                    contactEmail: 'E-Mail-Adresse',
                    contactMobile: 'Mobiltelefon',
                    contactTelephone: 'Festnetztelefon',                                
                },
                defaultJobPost: {
                    title: `Initiativbewerbungen`,
                    text: `Sie haben keine Stelle gefunden, die Ihrem Profil entspricht? Senden Sie Ihre Initiativbewerbung.`
                },
                fullName: 'Vollständiger Name',            
                readMore: 'Mehr lesen',
                viewMore: 'Mehr sehen',
                otherArticles: 'Andere Artikel…',
                seeAllNews: 'Alle Neuigkeiten ansehen',
                year: 'Jahr',
                copyright: 'Api AG. Alle Rechte vorbehalten',
                partnersTitle: 'Partner',
                partnersSubTitle: 'Entwicklung zu einem umfassenden Service',
                noResult: 'Kein Ergebnis',
                search: 'Suche',
                filters: 'Filter',
                return: 'Zurück',
                remoteSupport: `Remote-Support`,
                deleteEverything: 'Alles löschen',
                send: 'Abschicken',
                findUsOn: 'Finden Sie uns auf',
                subscribe: 'Unseren Newsletter abonnieren',
                form: {
                    firstName: 'Vorname *',
                    lastName: 'Name *',
                    topic: 'Betrifft',
                    email: 'E-Mail-Adresse',
                    message: 'Nachricht',
                    contactConfirmationMessage: 'Ihre Anfrage wurde erfolgreich versendet',
                    contactErrorMessage: 'Error',
                    selectOne: 'Kontaktaufnahme mit dem Vertrieb',
                    selectTwo: 'Kontaktaufnahme mit einem Bewerber',
                    selectThree: 'API-Informationen',
                    selectFour: 'Andere',
                },
                subscribeForm: {
                    success: 'Sie haben unseren Newsletter erfolgreich abonniert!',
                    error: 'Etwas ist schief gelaufen. Bitte versuche es erneut!',
                    alreadyExist: 'Du hast dich bereits abonniert!'
                },                
                deleteEverything: 'Alles löschen',
                contact: 'Kontakt',
                learnMore: 'Weitere Informationen',
                preferences: 'Einstellungen',
                necessaryCookies: 'Notwendige Cookies',
                analytics: 'Analytik',
                privacyPolicy: 'Datenschutzrichtlinie',
                supportClient: 'Kundenbetreuung :'
            }
        }
    }
}

export default AppConstants